// <auto-generated />
using System;
using GestaodePedidosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaodePedidosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917144304_AdicionaBebidasRestantes")]
    partial class AdicionaBebidasRestantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("GestaodePedidosAPI.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("GestaodePedidosAPI.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("GestaodePedidosAPI.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Nome = "Coca-Cola 350ml",
                            Preco = 6.00m
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Coca-Cola 1L",
                            Preco = 10.00m
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Coca-Cola 2L",
                            Preco = 15.00m
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Guaraná Antarctica 350mL",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Sprite 350mL",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Fanta Laranja 350ml",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Fanta Uva 350ml",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Suco de Laranja 500ml",
                            Preco = 10.00m
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Suco de Uva 500ml",
                            Preco = 12.00m
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Suco de Maracujá",
                            Preco = 15.00m
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Heineken Long Neck",
                            Preco = 10.00m
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Corona Long Neck",
                            Preco = 8.00m
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Budweiser Long Neck",
                            Preco = 9.00m
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Combo Família",
                            Preco = 80.00m
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Dogão no Prato",
                            Preco = 35.00m
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Combo Casal",
                            Preco = 45.00m
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Combo Kids",
                            Preco = 35.00m
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Combo Bacon",
                            Preco = 55.00m
                        });
                });

            modelBuilder.Entity("GestaodePedidosAPI.Models.ItemPedido", b =>
                {
                    b.HasOne("GestaodePedidosAPI.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaodePedidosAPI.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaodePedidosAPI.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
